#Tabellen-Spalten Konfiguration
#Mon Jun 22 17:28:15 CEST 2026
column_visible_0=true
column_visible_1=true
column_visible_10=true
column_visible_11=true
column_visible_12=false
column_visible_13=false
column_visible_14=false
column_visible_15=false
column_visible_16=false
column_visible_17=true
column_visible_18=false
column_visible_19=false
column_visible_2=true
column_visible_20=true
column_visible_21=true
column_visible_22=false
column_visible_23=false
column_visible_24=false
column_visible_25=false
column_visible_26=false
column_visible_27=false
column_visible_28=false
column_visible_29=false
column_visible_3=true
column_visible_30=true
column_visible_31=true
column_visible_32=true
column_visible_4=true
column_visible_5=true
column_visible_6=false
column_visible_7=false
column_visible_8=false
column_visible_9=false
